### ISSUE TITLE
Seeing the same four images over and over again.

### ISSUE THREAD

**Issue by lacooie** [planetlabs/planet-view-chrome-ext#47]
I downloaded this extension a couple weeks ago and realize I have been looking at the same few images whenever I open a new tab: Apple campus 5/20/17, Earthstone fire 7/5/2017, La Tuna fire 9/5/2017, Tesla Gigafactory 8/8/2017. That's it. Help?

Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by tschaub** [comment]
Thanks for the report!  I'm seeing the same and will investigate.

**Comment by rsimmon** [comment]
I’m pretty sure this is because only the most recent year of images are displayed by the plugin, and we’ve stopped adding images to the gallery.
